"""durable research lifecycle and versioned facts

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-06 13:52:50.745471

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("policy_key", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("requested_action", sa.String(length=16), nullable=True),
        sa.Column("control_version", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_batch_scope_key"), "batch", ["scope_key"], unique=False)
    op.create_index(op.f("ix_batch_status"), "batch", ["status"], unique=False)
    op.create_table(
        "collection_strategy",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "export_manifest",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("result_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("revision_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "issuer",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maintenance_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "market_quote_cache",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.create_table(
        "reporting_owner",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis_request",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_request_batch_id"), "analysis_request", ["batch_id"], unique=False
    )
    op.create_table(
        "feed_group_revision",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("group_key", sa.String(length=32), nullable=False),
        sa.Column("issuer_id", sa.String(length=10), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feed_group_revision_accepted_at"),
        "feed_group_revision",
        ["accepted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feed_group_revision_group_key"), "feed_group_revision", ["group_key"], unique=False
    )
    op.create_table(
        "filing",
        sa.Column("accession", sa.String(length=20), nullable=False),
        sa.Column("form", sa.String(length=8), nullable=False),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("issuer_id", sa.String(length=10), nullable=True),
        sa.Column("index_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version", sa.String(length=36), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuer.id"],
        ),
        sa.PrimaryKeyConstraint("accession"),
    )
    op.create_index(op.f("ix_filing_accepted_at"), "filing", ["accepted_at"], unique=False)
    op.create_index(op.f("ix_filing_issuer_id"), "filing", ["issuer_id"], unique=False)
    op.create_table(
        "import_preview",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hash"],
            ["source_object.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_dependency",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("prerequisite_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("job_id", "prerequisite_id"),
    )
    op.create_table(
        "security",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("issuer_id", sa.String(length=10), nullable=True),
        sa.Column("instrument", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=True),
        sa.Column("calendar", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("maintain", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_security_issuer_id"), "security", ["issuer_id"], unique=False)
    op.create_index(op.f("ix_security_symbol"), "security", ["symbol"], unique=False)
    op.create_table(
        "source_observation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hash"],
            ["source_object.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_observation_job_id"), "source_observation", ["job_id"], unique=False
    )
    op.create_table(
        "analysis_result",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("input_key", sa.String(length=64), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id", "security_id", "input_key"),
    )
    op.create_index(
        op.f("ix_analysis_result_analysis_id"), "analysis_result", ["analysis_id"], unique=False
    )
    op.create_table(
        "corporate_action",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hash"],
            ["source_object.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("security_id", "session_date", "kind", "value"),
    )
    op.create_index(
        op.f("ix_corporate_action_security_id"), "corporate_action", ["security_id"], unique=False
    )
    op.create_table(
        "coverage_segment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hash"],
            ["source_object.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_coverage_segment_security_id"), "coverage_segment", ["security_id"], unique=False
    )
    op.create_table(
        "earnings_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_quarter", sa.Integer(), nullable=True),
        sa.Column("announced_date", sa.Date(), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_precision", sa.String(length=24), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("is_estimate", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("security_id", "announced_date"),
    )
    op.create_index(
        op.f("ix_earnings_event_security_id"), "earnings_event", ["security_id"], unique=False
    )
    op.create_table(
        "filing_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("accession", sa.String(length=20), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["accession"],
            ["filing.accession"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hash"],
            ["source_object.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("accession", "source_hash", "parser_version"),
    )
    op.create_index(
        op.f("ix_filing_version_accession"), "filing_version", ["accession"], unique=False
    )
    op.create_table(
        "market_bar_revision",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("open", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("high", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("low", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("close", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("adj_close", sa.Numeric(precision=30, scale=12), nullable=True),
        sa.Column("volume", sa.Numeric(precision=32, scale=4), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_hash"],
            ["source_object.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("security_id", "session_date", "provider", "record_hash"),
    )
    op.create_index(
        op.f("ix_market_bar_revision_security_id"),
        "market_bar_revision",
        ["security_id"],
        unique=False,
    )
    op.create_table(
        "price_dataset_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("basis", sa.String(length=48), nullable=False),
        sa.Column("basis_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_dataset_version_security_id"),
        "price_dataset_version",
        ["security_id"],
        unique=False,
    )
    op.create_table(
        "request_scope",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("wait_reason", sa.Text(), nullable=True),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "symbol"),
    )
    op.create_index(op.f("ix_request_scope_batch_id"), "request_scope", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_request_scope_security_id"), "request_scope", ["security_id"], unique=False
    )
    op.create_table(
        "security_identifier",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "symbol", "valid_from"),
    )
    op.create_index(
        op.f("ix_security_identifier_security_id"),
        "security_identifier",
        ["security_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_security_identifier_symbol"), "security_identifier", ["symbol"], unique=False
    )
    op.create_table(
        "batch_job",
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["request_scope.id"],
        ),
        sa.PrimaryKeyConstraint("scope_id", "job_id"),
    )
    op.create_table(
        "dataset_bar",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("bar_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["bar_id"],
            ["market_bar_revision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["price_dataset_version.id"],
        ),
        sa.PrimaryKeyConstraint("dataset_id", "session_date"),
    )
    op.create_table(
        "filing_owner",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=10), nullable=False),
        sa.Column("relationship", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["reporting_owner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["filing_version.id"],
        ),
        sa.PrimaryKeyConstraint("version_id", "owner_id"),
    )
    op.create_table(
        "transaction_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("issuer_id", sa.String(length=10), nullable=False),
        sa.Column("accession", sa.String(length=20), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("row_key", sa.String(length=100), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("owner_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("replaces_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["accession"],
            ["filing.accession"],
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replaces_id"],
            ["transaction_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["filing_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id", "row_key"),
    )
    op.create_index(
        "ix_event_issuer_date",
        "transaction_event",
        ["issuer_id", "transaction_date", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_event_accepted_at"), "transaction_event", ["accepted_at"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_event_accession"), "transaction_event", ["accession"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_event_issuer_id"), "transaction_event", ["issuer_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_event_transaction_date"),
        "transaction_event",
        ["transaction_date"],
        unique=False,
    )
    op.create_table(
        "amendment_relation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("accession", sa.String(length=20), nullable=False),
        sa.Column("original_event_id", sa.String(length=36), nullable=True),
        sa.Column("amended_event_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["accession"],
            ["filing.accession"],
        ),
        sa.ForeignKeyConstraint(
            ["amended_event_id"],
            ["transaction_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_event_id"],
            ["transaction_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("amendment_relation")
    op.drop_index(op.f("ix_transaction_event_transaction_date"), table_name="transaction_event")
    op.drop_index(op.f("ix_transaction_event_issuer_id"), table_name="transaction_event")
    op.drop_index(op.f("ix_transaction_event_accession"), table_name="transaction_event")
    op.drop_index(op.f("ix_transaction_event_accepted_at"), table_name="transaction_event")
    op.drop_index("ix_event_issuer_date", table_name="transaction_event")
    op.drop_table("transaction_event")
    op.drop_table("filing_owner")
    op.drop_table("dataset_bar")
    op.drop_table("batch_job")
    op.drop_index(op.f("ix_security_identifier_symbol"), table_name="security_identifier")
    op.drop_index(op.f("ix_security_identifier_security_id"), table_name="security_identifier")
    op.drop_table("security_identifier")
    op.drop_index(op.f("ix_request_scope_security_id"), table_name="request_scope")
    op.drop_index(op.f("ix_request_scope_batch_id"), table_name="request_scope")
    op.drop_table("request_scope")
    op.drop_index(op.f("ix_price_dataset_version_security_id"), table_name="price_dataset_version")
    op.drop_table("price_dataset_version")
    op.drop_index(op.f("ix_market_bar_revision_security_id"), table_name="market_bar_revision")
    op.drop_table("market_bar_revision")
    op.drop_index(op.f("ix_filing_version_accession"), table_name="filing_version")
    op.drop_table("filing_version")
    op.drop_index(op.f("ix_earnings_event_security_id"), table_name="earnings_event")
    op.drop_table("earnings_event")
    op.drop_index(op.f("ix_coverage_segment_security_id"), table_name="coverage_segment")
    op.drop_table("coverage_segment")
    op.drop_index(op.f("ix_corporate_action_security_id"), table_name="corporate_action")
    op.drop_table("corporate_action")
    op.drop_index(op.f("ix_analysis_result_analysis_id"), table_name="analysis_result")
    op.drop_table("analysis_result")
    op.drop_index(op.f("ix_source_observation_job_id"), table_name="source_observation")
    op.drop_table("source_observation")
    op.drop_index(op.f("ix_security_symbol"), table_name="security")
    op.drop_index(op.f("ix_security_issuer_id"), table_name="security")
    op.drop_table("security")
    op.drop_table("job_dependency")
    op.drop_table("import_preview")
    op.drop_index(op.f("ix_filing_issuer_id"), table_name="filing")
    op.drop_index(op.f("ix_filing_accepted_at"), table_name="filing")
    op.drop_table("filing")
    op.drop_index(op.f("ix_feed_group_revision_group_key"), table_name="feed_group_revision")
    op.drop_index(op.f("ix_feed_group_revision_accepted_at"), table_name="feed_group_revision")
    op.drop_table("feed_group_revision")
    op.drop_index(op.f("ix_analysis_request_batch_id"), table_name="analysis_request")
    op.drop_table("analysis_request")
    op.drop_table("user_preferences")
    op.drop_table("reporting_owner")
    op.drop_table("market_quote_cache")
    op.drop_table("maintenance_run")
    op.drop_table("issuer")
    op.drop_table("feed_session")
    op.drop_table("export_manifest")
    op.drop_table("collection_strategy")
    op.drop_index(op.f("ix_batch_status"), table_name="batch")
    op.drop_index(op.f("ix_batch_scope_key"), table_name="batch")
    op.drop_table("batch")
    # ### end Alembic commands ###
