import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("../src/chartSampleLabel.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { chartSampleLabel } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
assert.equal(chartSampleLabel([]),null);
assert.equal(chartSampleLabel([{n:0},{n:0}]),null);
assert.equal(chartSampleLabel([{n:0},{n:1}]),"单一样本路径（N=1）");
assert.equal(chartSampleLabel([{n:2},{n:1}]),"历史中位路径");
console.log("chart sample labels passed");
