import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("../src/comparableResults.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { comparableResults } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const item = (symbol, is_current, version, cutoff, basis = "SPLIT_ONLY") => ({ symbol, is_current, result_id: symbol, data: { metadata: { calculation_version: version, cutoff_date: cutoff, price_basis: basis, comparison: "complete", calendar_version: "xnys" } } });
const a = item("AAPL", true, "research-v10-time-source-attribution", "2026-09-23");
const b = item("MSFT", true, "research-v10-time-source-attribution", "2026-09-23");
const old = item("NVDA", false, "research-v9-fiscal-kind-evidence", "2026-09-23");
const wrongCutoff = item("COST", true, "research-v10-time-source-attribution", "2026-09-22");
const wrongBasis = item("AMZN", true, "research-v10-time-source-attribution", "2026-09-23", "RAW");
const all = [a,b,old,wrongCutoff,wrongBasis];
assert.deepEqual(comparableResults(all, a, all.map(x => x.symbol)).map(x => x.symbol), ["AAPL","MSFT"]);
assert.deepEqual(comparableResults(all, old, all.map(x => x.symbol)), []);
console.log("cross security charts exclude stale version, cutoff and price basis");
