import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("../src/eventPromptConditions.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { eventPromptConditions, eventPromptDraftKey, eventConditionsForLanguage, eventCommonYearsLabel, restoreEventPromptConditions } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const params = new URLSearchParams("company=Apple&ticker=AAPL&event_type=earnings&year_start=2020&year_end=2025&quarter=2");
const zh = eventPromptConditions(params,"earnings","zh");
const en = eventPromptConditions(params,"earnings","en");
assert.match(zh,/沟通语言：中文.*Apple.*AAPL.*仅财季：Q2.*2020—2025/);
assert.match(en,/Communication language: English.*Apple.*AAPL.*Fiscal quarter: only Q2.*2020–2025/);
assert.doesNotMatch(en,/研究类型|财季|年份/);
const apple = new URLSearchParams("kind=custom&company=Apple%20Inc.&ticker=AAPL&event_type=developer_keynote&year_start=2023&year_end=2025");
const oracle = new URLSearchParams("kind=custom&company=Oracle&ticker=ORCL&quarter=1");
assert.notEqual(eventPromptDraftKey(apple, "custom"), eventPromptDraftKey(oracle, "custom"));
assert.notEqual(eventPromptDraftKey(apple, "custom"), eventPromptDraftKey(new URLSearchParams(), "custom"));
assert.equal(eventPromptDraftKey(new URLSearchParams(), "custom"), "event-draft:custom:new");
assert.equal(eventPromptDraftKey(new URLSearchParams("draft=abc&company=Apple"), "custom"), "event-draft:custom:new:abc");
assert.equal(eventPromptDraftKey(new URLSearchParams("set=xyz&company=Apple"), "custom"), "event-draft:custom:xyz");
assert.equal(eventPromptDraftKey(new URLSearchParams("year_start=2023&company=Apple"), "custom"), eventPromptDraftKey(new URLSearchParams("company=Apple&year_start=2023"), "custom"));
console.log("event prompt conditions passed");

const native = new URLSearchParams("kind=earnings&tickers=AAPL&historical_years=8&years=2024&current_fiscal_year=2025&quarter=2");
for (const language of ["zh", "en"]) {
  const text = eventPromptConditions(native, "earnings", language);
  assert.match(text, /2024/);
  assert.match(text, /2025/);
  assert.doesNotMatch(text, /过去 8|past 8|确认具体起止|confirm exact/);
  assert.match(text, language === "zh" ? /当前对照财年：2025.*纳入资料查询.*不计入历史/ : /Current comparison fiscal year: 2025.*include.*not.*historical/i);
}
const disjoint = new URLSearchParams("tickers=AAPL&years=2020,2024&current_fiscal_year=2025&quarter=2");
assert.match(eventPromptConditions(disjoint, "earnings", "zh"), /2020、2024/);
assert.match(eventPromptConditions(disjoint, "earnings", "en"), /2020, 2024/);
assert.doesNotMatch(eventPromptConditions(disjoint, "earnings", "zh"), /年份：2020—2024/);
assert.match(eventPromptConditions(disjoint, "earnings", "zh"), /非连续.*先.*确认.*不得.*扩大/);
assert.match(eventPromptConditions(disjoint, "earnings", "en"), /non-contiguous.*ask.*confirm.*not.*widen/i);
const excluded = new URLSearchParams("tickers=AAPL&years=2020,2021,2022&excluded_years=2021&quarter=2");
assert.match(eventPromptConditions(excluded, "earnings", "zh"), /排除历史财年：2021/);
assert.match(eventPromptConditions(excluded, "earnings", "zh"), /非连续/);
assert.match(eventPromptConditions(new URLSearchParams("years=2024&quarter=2"), "earnings", "zh"), /当前对照财年未知.*不推断/);
const autoZh = eventPromptConditions(native, "earnings", "zh");
assert.equal(eventConditionsForLanguage(autoZh, native, "earnings", "zh", "en"), eventPromptConditions(native, "earnings", "en"));
assert.equal(eventConditionsForLanguage("只查 Apple Q2，保留我的备注", native, "earnings", "zh", "en"), "只查 Apple Q2，保留我的备注");
assert.notEqual(eventPromptDraftKey(new URLSearchParams("years=2020,2024"), "earnings"), eventPromptDraftKey(new URLSearchParams("years=2021,2024"), "earnings"));
assert.equal(eventCommonYearsLabel([2]), "只比较所请求财季的共同完整财年（Q2；各窗口分别核对）");
assert.equal(eventCommonYearsLabel([2, 4]), "只比较所请求财季的共同完整财年（Q2、Q4；各窗口分别核对）");
assert.equal(eventCommonYearsLabel([1, 2, 3, 4]), "只比较四季共同完整财年（Q1—Q4；各窗口分别核对）");
assert.equal(eventCommonYearsLabel(undefined), "只比较所请求财季的共同完整财年（范围待确认；各窗口分别核对）");
console.log("native year scope, language preservation and fiscal cohort labels passed");

const legacyZh = "沟通语言：中文；研究类型：财报业绩首次发布；证券代码: AAPL；希望研究过去 8 个完整财年，请确认具体起止年份。；仅财季：Q2";
const legacyEn = "Communication language: English; Research type: earnings first release; Security ticker: AAPL; Study the past 8 complete fiscal years; confirm exact start and end years.; Fiscal quarter: only Q2";
assert.equal(restoreEventPromptConditions(legacyZh, native, "earnings", "zh"), autoZh);
assert.equal(restoreEventPromptConditions(legacyEn, native, "earnings", "en"), eventPromptConditions(native, "earnings", "en"));
assert.equal(restoreEventPromptConditions(legacyZh + "；另保留我的条件", native, "earnings", "zh"), legacyZh + "；另保留我的条件");
assert.equal(eventConditionsForLanguage(legacyZh, native, "earnings", "zh", "en"), eventPromptConditions(native, "earnings", "en"));
console.log("legacy generated drafts upgrade without replacing free-form conditions");
