import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const source = readFileSync(new URL("../src/eventExportIdentity.ts", import.meta.url), "utf8");
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { eventExportIdentity } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const native = eventExportIdentity({ params: { kind: "earnings", quarter: 2 } }, "AAPL", true);
assert.equal(native.symbol, "AAPL");
assert.equal(native.factVersion, "原生财报事实随结果冻结");
assert.doesNotMatch(`${native.symbol} ${native.factVersion}`, /证券 —|事件事实版本 —/);
const custom = eventExportIdentity({ symbol: "MSFT", event_version_id: "verified-v2" });
assert.equal(custom.symbol, "MSFT");
assert.equal(custom.factVersion, "事件资料版本 verified-v2");
assert.equal(eventExportIdentity({}).symbol, "待核对");
console.log("event export identity passed");
