import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
const compiled = ts.transpileModule(readFileSync(new URL("../src/eventScopeCompatibility.ts", import.meta.url), "utf8"), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const { eventScopeConflict, eventAnalysisForImportedScope } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`);
const saved = Object.freeze({kind:"event_dates",event_version:1,years:Object.freeze([2018,2019,2020,2021,2022,2023,2024,2025]), historical_years:8, excluded_years:Object.freeze([2020]), cutoff_date:"2026-09-23", date_window:"after5", date_category:"developer_keynote", benchmark:"^GSPC", common_years:false, current_fiscal_year:2026, include_unverified:false});
const scope = {year_start:2024,year_end:2024};
assert.deepEqual(eventScopeConflict(saved,scope), {start:2024,end:2024,outsideYears:[2018,2019,2020,2021,2022,2023,2025]});
assert.deepEqual(eventScopeConflict({...saved,years:[2018,2024]},scope).outsideYears,[2018], "explicit nonconsecutive selections receive the same choice, never a default-year assumption");
assert.deepEqual(eventScopeConflict({...saved,years:[2020,2024],excluded_years:[2020]},scope).outsideYears,[2020], "excluded years still fail backend pre-exclusion range validation");
assert.equal(eventScopeConflict({...saved,years:[2024]},scope),null);
assert.equal(eventScopeConflict({...saved,years:undefined},scope),null);
assert.equal(eventScopeConflict(saved,{}),null);
assert.equal(eventScopeConflict({...saved,years:["2024"]},scope),null, "malformed values are not normalized or guessed");
const next = eventAnalysisForImportedScope(saved,scope);
assert.equal(next.years,undefined,"explicit migration uses the imported range through backend validation");
assert.equal(next.cutoff_date,undefined,"explicit follow-latest migration uses latest completed session");
assert.equal(next.historical_years,1);
assert.equal(next.version,1);
assert.deepEqual(next.excluded_years,[2020]);
for(const key of ["date_window","date_category","benchmark","common_years","current_fiscal_year","include_unverified"]) assert.equal(next[key],saved[key]);
assert.deepEqual(saved.years,[2018,2019,2020,2021,2022,2023,2024,2025],"old snapshot/request remains untouched");
assert.equal(saved.cutoff_date,"2026-09-23");
assert.equal(eventAnalysisForImportedScope({...saved,date_window:"day0"},scope).date_window,"day0","window choice is preserved");
const fiscalScope={fiscal_year_start:2023,fiscal_year_end:2025};
assert.deepEqual(eventScopeConflict({...saved,years:[2022,2023,2025]},fiscalScope).outsideYears,[2022]);
assert.equal(eventAnalysisForImportedScope(saved,fiscalScope).historical_years,3);
assert.throws(()=>eventAnalysisForImportedScope(saved,{}), /资料范围/);
console.log("event scope compatibility: explicit choice, immutable old conditions, windows, exclusions and fiscal scope passed");
